insert into animal (name) values ('Marshbird, brown and yellow');
insert into animal (name) values ('Worm snake (unidentified)');
insert into animal (name) values ('Dragon, netted rock');
insert into animal (name) values ('Lechwe, kafue flats');
insert into animal (name) values ('Whale, long-finned pilot');
insert into animal (name) values ('Wolf spider');
insert into animal (name) values ('Frilled dragon');
insert into animal (name) values ('Bee-eater, carmine');
insert into animal (name) values ('Penguin, magellanic');
insert into animal (name) values ('Tortoise, indian star');
insert into animal (name) values ('Vulture, white-headed');
insert into animal (name) values ('Flamingo, lesser');
insert into animal (name) values ('Laughing dove');
insert into animal (name) values ('Iguana, marine');
insert into animal (name) values ('Cape starling');
insert into animal (name) values ('Bent-toed gecko');
insert into animal (name) values ('Southern elephant seal');
insert into animal (name) values ('Vulture, white-rumped');
insert into animal (name) values ('Black spider monkey');
insert into animal (name) values ('Quail, gambel''s');
insert into animal (name) values ('Blesbok');
insert into animal (name) values ('Gila monster');
insert into animal (name) values ('Asian lion');
insert into animal (name) values ('Gnu, brindled');
insert into animal (name) values ('Rattlesnake, dusky');
insert into animal (name) values ('Magnificent frigate bird');
insert into animal (name) values ('Crane, sandhill');
insert into animal (name) values ('Greater rhea');
insert into animal (name) values ('Common nighthawk');
insert into animal (name) values ('Blesbok');
insert into animal (name) values ('Rabbit, eastern cottontail');
insert into animal (name) values ('Cormorant (unidentified)');
insert into animal (name) values ('Lizard, blue-tongued');
insert into animal (name) values ('Netted rock dragon');
insert into animal (name) values ('Springbuck');
insert into animal (name) values ('Bald eagle');
insert into animal (name) values ('Squirrel, indian giant');
insert into animal (name) values ('Barrows goldeneye');
insert into animal (name) values ('Wolf, timber');
insert into animal (name) values ('Black curlew');
insert into animal (name) values ('Wolf spider');
insert into animal (name) values ('Antelope, sable');
insert into animal (name) values ('Giraffe');
insert into animal (name) values ('Skimmer, four-spotted');
insert into animal (name) values ('Cape wild cat');
insert into animal (name) values ('Eastern box turtle');
insert into animal (name) values ('Banded mongoose');
insert into animal (name) values ('Puffin, horned');
insert into animal (name) values ('Least chipmunk');
insert into animal (name) values ('Shark, blue');
insert into animal (name) values ('Whale, southern right');
insert into animal (name) values ('Squirrel, nelson ground');
insert into animal (name) values ('European spoonbill');
insert into animal (name) values ('Rhesus macaque');
insert into animal (name) values ('Red sheep');
insert into animal (name) values ('Hoary marmot');
insert into animal (name) values ('Crane, sandhill');
insert into animal (name) values ('Kangaroo, red');
insert into animal (name) values ('Frilled dragon');
insert into animal (name) values ('Asian lion');
insert into animal (name) values ('Scaly-breasted lorikeet');
insert into animal (name) values ('Godwit, hudsonian');
insert into animal (name) values ('Paddy heron (unidentified)');
insert into animal (name) values ('European shelduck');
insert into animal (name) values ('European wild cat');
insert into animal (name) values ('Collared peccary');
insert into animal (name) values ('Grenadier, common');
insert into animal (name) values ('Asian lion');
insert into animal (name) values ('Goldeneye, common');
insert into animal (name) values ('Zorro, azara''s');
insert into animal (name) values ('Weaver, lesser masked');
insert into animal (name) values ('Lemur, ring-tailed');
insert into animal (name) values ('Roadrunner, greater');
insert into animal (name) values ('Squirrel, pine');
insert into animal (name) values ('Crown of thorns starfish');
insert into animal (name) values ('Squirrel glider');
insert into animal (name) values ('Heron, green');
insert into animal (name) values ('Western pygmy possum');
insert into animal (name) values ('Iguana, marine');
insert into animal (name) values ('Striped hyena');
insert into animal (name) values ('Gonolek, burchell''s');
insert into animal (name) values ('Shelduck, european');
insert into animal (name) values ('Turaco, violet-crested');
insert into animal (name) values ('Sheep, stone');
insert into animal (name) values ('Campo flicker');
insert into animal (name) values ('Sloth, pale-throated three-toed');
insert into animal (name) values ('Chuckwalla');
insert into animal (name) values ('Egyptian cobra');
insert into animal (name) values ('Asian openbill');
insert into animal (name) values ('Common duiker');
insert into animal (name) values ('Galapagos hawk');
insert into animal (name) values ('Black-throated cardinal');
insert into animal (name) values ('Giant armadillo');
insert into animal (name) values ('Anteater, giant');
insert into animal (name) values ('Southern black-backed gull');
insert into animal (name) values ('Cow, scottish highland');
insert into animal (name) values ('Wallaby, tammar');
insert into animal (name) values ('Sportive lemur');
insert into animal (name) values ('African jacana');
insert into animal (name) values ('Raven, white-necked');
