insert into movie (id, title, year) values (1, 'Angel on My Shoulder', 2006);
insert into movie (id, title, year) values (2, 'Faces of Death', 2006);
insert into movie (id, title, year) values (3, 'Con, The', 2002);
insert into movie (id, title, year) values (4, 'Prancer', 1994);
insert into movie (id, title, year) values (5, 'Two Girls and a Guy', 1999);
insert into movie (id, title, year) values (6, 'Barocco', 2000);
insert into movie (id, title, year) values (7, 'Above Suspicion', 1996);
insert into movie (id, title, year) values (8, 'Brothers Grimm, The', 2001);
insert into movie (id, title, year) values (9, 'Human Factor, The', 1994);
insert into movie (id, title, year) values (10, 'Eulogy', 1992);
insert into movie (id, title, year) values (11, 'Guns of the Magnificent Seven', 2007);
insert into movie (id, title, year) values (12, 'Faithful', 2005);
insert into movie (id, title, year) values (13, 'Strawberry Blonde, The', 2006);
insert into movie (id, title, year) values (14, 'Prince & Me, The', 2009);
insert into movie (id, title, year) values (15, 'Chambermaid on the Titanic, The (Femme de chambre du Titanic, La)', 2009);
insert into movie (id, title, year) values (16, 'Cherry Tree Lane', 2000);
insert into movie (id, title, year) values (17, 'State of Things, The (Stand der Dinge, Der)', 2006);
insert into movie (id, title, year) values (18, 'Striking Range', 1999);
insert into movie (id, title, year) values (19, 'Genghis Blues', 2002);
insert into movie (id, title, year) values (20, 'Age of Innocence, The', 1986);
insert into movie (id, title, year) values (21, 'Crazy for Christmas', 2000);
insert into movie (id, title, year) values (22, 'Search and Destroy', 1994);
insert into movie (id, title, year) values (23, 'Temptation (Tentação)', 2007);
insert into movie (id, title, year) values (24, 'Evil - In the Time of Heroes (To kako - Stin epohi ton iroon)', 1977);
insert into movie (id, title, year) values (25, 'Profound Desires of the Gods (Kamigami no fukaki yokubo) ', 2007);
insert into movie (id, title, year) values (26, 'Dog Day (Canicule)', 2001);
insert into movie (id, title, year) values (27, 'Human Race, The', 2010);
insert into movie (id, title, year) values (28, 'RocketMan (a.k.a. Rocket Man)', 1990);
insert into movie (id, title, year) values (29, 'Maybe Baby', 2009);
insert into movie (id, title, year) values (30, 'Music of Chance, The', 2010);
insert into movie (id, title, year) values (31, 'Confession', 2001);
insert into movie (id, title, year) values (32, 'To Sir with Love', 2009);
insert into movie (id, title, year) values (33, 'Drive Angry', 1997);
insert into movie (id, title, year) values (34, 'Time and Tide (Seunlau Ngaklau)', 2004);
insert into movie (id, title, year) values (35, 'French Minister, The (Quai d''Orsay)', 2005);
insert into movie (id, title, year) values (36, 'Stille nacht', 2004);
insert into movie (id, title, year) values (37, 'Amen', 1996);
insert into movie (id, title, year) values (38, 'How I Ended This Summer (Kak ya provyol etim letom)', 2003);
insert into movie (id, title, year) values (39, 'Carried Away', 1992);
insert into movie (id, title, year) values (40, 'Aces and Eights', 2009);
insert into movie (id, title, year) values (41, 'Human Centipede II (Full Sequence), The', 2007);
insert into movie (id, title, year) values (42, 'Trust Me', 1988);
insert into movie (id, title, year) values (43, 'Sabotage', 2012);
insert into movie (id, title, year) values (44, 'Grudge Match', 2000);
insert into movie (id, title, year) values (45, 'Ruby & Quentin (Tais-toi!)', 1985);
insert into movie (id, title, year) values (46, 'Mummy: Tomb of the Dragon Emperor, The', 1991);
insert into movie (id, title, year) values (47, 'Phar Lap', 2010);
insert into movie (id, title, year) values (48, 'My Foolish Heart', 1984);
insert into movie (id, title, year) values (49, 'Of Horses and Men', 2000);
insert into movie (id, title, year) values (50, 'The Karen Carpenter Story', 2001);
insert into movie (id, title, year) values (51, 'Callan', 2005);
insert into movie (id, title, year) values (52, 'Ill Manors', 1997);
insert into movie (id, title, year) values (53, 'Tenebre', 2008);
insert into movie (id, title, year) values (54, 'Dark Forces (Harlequin)', 2009);
insert into movie (id, title, year) values (55, 'Azumi', 2006);
insert into movie (id, title, year) values (56, 'Hotel for Dogs', 2006);
insert into movie (id, title, year) values (57, 'Hippie Revolution, The', 2005);
insert into movie (id, title, year) values (58, 'Pinky', 1997);
insert into movie (id, title, year) values (59, 'Rob the Mob', 2004);
insert into movie (id, title, year) values (60, 'Sword and the Dragon, The (Ilya Muromets)', 2007);
insert into movie (id, title, year) values (61, 'Architect, The', 1996);
insert into movie (id, title, year) values (62, 'Down to Earth', 2007);
insert into movie (id, title, year) values (63, 'Cotton Mary', 2000);
insert into movie (id, title, year) values (64, 'Why Not? (Eijanaika)', 1998);
insert into movie (id, title, year) values (65, 'Nun''s Story, The', 2005);
insert into movie (id, title, year) values (66, 'House of the Seven Gables, The', 2002);
insert into movie (id, title, year) values (67, 'Here Comes Peter Cottontail ', 1999);
insert into movie (id, title, year) values (68, 'Prophet''s Prey', 2003);
insert into movie (id, title, year) values (69, 'Fuck You, Goethe (Fack Ju Göhte)', 2007);
insert into movie (id, title, year) values (70, 'Easy', 2004);
insert into movie (id, title, year) values (71, 'Eros Plus Massacre (Erosu purasu Gyakusatsu)', 1994);
insert into movie (id, title, year) values (72, 'Tube Tales', 1996);
insert into movie (id, title, year) values (73, 'Five Corners', 2005);
insert into movie (id, title, year) values (74, 'Candy', 2011);
insert into movie (id, title, year) values (75, 'Bang the Drum Slowly', 2007);
insert into movie (id, title, year) values (76, 'Butch and Sundance: The Early Days', 2008);
insert into movie (id, title, year) values (77, 'Antoine and Colette (Antoine et Colette)', 2005);
insert into movie (id, title, year) values (78, 'Place in the Sun, A (En plats i solen)', 2002);
insert into movie (id, title, year) values (79, 'Venus', 1992);
insert into movie (id, title, year) values (80, 'Angels and Insects', 1991);
insert into movie (id, title, year) values (81, 'Package, The', 2001);
insert into movie (id, title, year) values (82, 'Christmas Vacation (National Lampoon''s Christmas Vacation)', 1987);
insert into movie (id, title, year) values (83, 'Return of Doctor X, The', 2012);
insert into movie (id, title, year) values (84, 'Soldier''s Plaything, A', 1995);
insert into movie (id, title, year) values (85, 'Wedding Gift, The', 2003);
insert into movie (id, title, year) values (86, 'Moonlight and Cactus', 1994);
insert into movie (id, title, year) values (87, 'Physical Evidence', 2009);
insert into movie (id, title, year) values (88, 'Normal', 1998);
insert into movie (id, title, year) values (89, 'Real Blonde, The', 2003);
insert into movie (id, title, year) values (90, 'The D Train', 2007);
insert into movie (id, title, year) values (91, 'Lettera Amorosa', 2000);
insert into movie (id, title, year) values (92, 'Alex and Emma', 1995);
insert into movie (id, title, year) values (93, 'The Derby Stallion', 2001);
insert into movie (id, title, year) values (94, 'Trance', 2004);
insert into movie (id, title, year) values (95, 'What Richard Did', 1993);
insert into movie (id, title, year) values (96, 'Naturally Native', 2011);
insert into movie (id, title, year) values (97, 'Great Caruso, The', 2007);
insert into movie (id, title, year) values (98, 'Get Educated: Paathshaala', 2004);
insert into movie (id, title, year) values (99, 'Putty Hill', 2010);
insert into movie (id, title, year) values (100, 'The Secret of Convict Lake', 2008);
