insert into person (id, fullname, job, gender, city, salary, birthday) values (1, 'Riobard Folli', 'Project Manager', 'Male', 'Berlin', 10022, '1970-02-19');
insert into person (id, fullname, job, gender, city, salary, birthday) values (2, 'Harlin McAuslan', 'Personal Trainer', 'Male', 'Stockholm', 7094, '1963-02-09');
insert into person (id, fullname, job, gender, city, salary, birthday) values (3, 'Courtnay Willson', 'Photographer', 'Male', 'Wellington', 17726, '1973-08-01');
insert into person (id, fullname, job, gender, city, salary, birthday) values (4, 'Aleece Colquyte', 'Accountant', 'Female', 'London', 19776, '1983-05-16');
insert into person (id, fullname, job, gender, city, salary, birthday) values (5, 'Gustaf Allenby', 'Pole Dancer', 'Male', 'Washington DC', 12541, '1967-07-18');
insert into person (id, fullname, job, gender, city, salary, birthday) values (6, 'Hyacinthie Gayler', 'Soldier', 'Female', 'Helsinki', 1836, '1946-03-28');
insert into person (id, fullname, job, gender, city, salary, birthday) values (7, 'Brena Barradell', 'Soldier', 'Female', 'Hanoi', 1599, '1969-04-18');
insert into person (id, fullname, job, gender, city, salary, birthday) values (8, 'Babara Speenden', 'Film Maker', 'Female', 'Canberra', 8511, '1967-12-08');
insert into person (id, fullname, job, gender, city, salary, birthday) values (9, 'Linnie Labitt', 'Bartender', 'Female', 'Wellington', 17581, '1978-02-26');
insert into person (id, fullname, job, gender, city, salary, birthday) values (10, 'Marcello Gofford', 'Taxi Driver', 'Male', 'Canberra', 4388, '1997-08-01');
insert into person (id, fullname, job, gender, city, salary, birthday) values (11, 'Christopher Bohlens', 'Soldier', 'Male', 'Jakarta', 908, '1969-04-21');
insert into person (id, fullname, job, gender, city, salary, birthday) values (12, 'Lavena Wattam', 'Personal Trainer', 'Female', 'Cairo', 9415, '1962-12-01');
insert into person (id, fullname, job, gender, city, salary, birthday) values (13, 'Cassandra Skurm', 'Film Maker', 'Female', 'Berlin', 18315, '1975-11-04');
insert into person (id, fullname, job, gender, city, salary, birthday) values (14, 'Vern Deniso', 'Developer', 'Male', 'Copenhagen', 19457, '1946-12-21');
insert into person (id, fullname, job, gender, city, salary, birthday) values (15, 'Hynda Clearley', 'Photographer', 'Female', 'Buenos Aires', 7000, '1990-09-24');
insert into person (id, fullname, job, gender, city, salary, birthday) values (16, 'Michele Fairtlough', 'Unemployment', 'Male', 'Bejing', 968, '1960-08-25');
insert into person (id, fullname, job, gender, city, salary, birthday) values (17, 'Clemmie Pfeuffer', 'Musician', 'Male', 'Amsterdam', 5973, '1994-02-19');
insert into person (id, fullname, job, gender, city, salary, birthday) values (18, 'Susana Dionsetti', 'Project Manager', 'Female', 'Stockholm', 4279, '1996-08-23');
insert into person (id, fullname, job, gender, city, salary, birthday) values (19, 'Mischa Murrigan', 'Accountant', 'Male', 'Kuala Lumpur', 15198, '1999-06-15');
insert into person (id, fullname, job, gender, city, salary, birthday) values (20, 'Salvidor Wheble', 'Film Maker', 'Male', 'Zurich', 14158, '1983-06-25');